"""new field in the user table

Revision ID: 402ba78eccac
Revises: 585086e86f94
Create Date: 2024-03-19 01:58:10.950161

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '402ba78eccac'
down_revision = '585086e86f94'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('about_me', sa.String(length=140), nullable=True))
        batch_op.add_column(sa.Column('last_seen', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('last_seen')
        batch_op.drop_column('about_me')

    # ### end Alembic commands ###
